### ISSUE TITLE
获取轮播图数据时出现错误

### ISSUE THREAD

**Issue by huangkr03** [QuanhuZeYu/koishi-plugin-arknights-wiki#1]
```shell
arknights-wiki 获取轮播图数据时出现错误: TypeError: Cannot read properties of undefined (reading 'evaluate') at Object.getCarouselData (/koishi/node_modules/@quanhuzeyu/koishi-plugin-arknights-wiki/lib/index.js:183:44) at Object.getCarouselData (/koishi/node_modules/@quanhuzeyu/koishi-plugin-arknights-wiki/lib/index.js:461:56) at _Command.<anonymous> (/koishi/node_modules/@quanhuzeyu/koishi-plugin-arknights-wiki/lib/index.js:573:22) at Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1083:27) at argv.next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1094:30) at _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1097:33)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2064:22 at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:1973:22) at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)
```
需要安装的插件我都装了的
![image](https://github.com/user-attachments/assets/95ab74c3-8cb6-4cf2-90ce-b5dc77365a6a)

**Comment by lonelyion** [comment]
同样的问题
